version: '3'

services:
    web:
        build: 
            # Use the current working directory 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
        stdin_open: true