---
    - name: Checkout srouce code
      git: repo="{{ git_app_url }}"
           dest="{{ app_provisioning_dir }}"
           version="{{ app_provisioning_branch }}"
           force=yes

    - name: Copy Properties file
      template: src="app.properties"
                dest="{{ app_provisioning_dir }}/app.properties"

